### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by BennerZhang** [VernonVan/PPStickerKeyboard#1]
是在模拟器上运行时，按下表情按钮发现闪退了。具体操作如下：
运行iPhone 6 plus,ios 10.0版本的，点击表情键盘后再点击emoji和键盘切换的那个图标后闪退。
故障代码是：
PPStickerKeyboard[40460:4527147] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIWindow safeAreaInsets]: unrecognized selector sent to instance 0x7fe7a16115e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001034e134b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000102f4221e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000103550f34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000103466c15 ___forwarding___ + 1013
	4   CoreFoundation                      0x00000001034f4008 __forwarding_prep_1___ + 120
	5   PPStickerKeyboard                   0x0000000102946f6d -[PPStickerKeyboard heightThatFits] + 157
	6   PPStickerKeyboard                   0x0000000102941717 -[PPStickerInputView stickerKeyboard] + 247
	7   PPStickerKeyboard                   0x0000000102940e7a -[PPStickerInputView changeKeyboardTo:] + 794
	8   PPStickerKeyboard                   0x000000010294282b -[PPStickerInputView toggleKeyboardDidClick:] + 107
	9   UIKit                               0x0000000104016b88 -[UIApplication sendAction:to:from:forEvent:] + 83
	10  UIKit                               0x000000010419c2b2 -[UIControl sendAction:to:forEvent:] + 67
	11  UIKit                               0x000000010419c5cb -[UIControl _sendActionsForEvents:withEvent:] + 444
	12  UIKit                               0x000000010419b4c7 -[UIControl touchesEnded:withEvent:] + 668
	13  UIKit                               0x00000001040840d5 -[UIWindow _sendTouchesForEvent:] + 2747
	14  UIKit                               0x00000001040857c3 -[UIWindow sendEvent:] + 4011
	15  UIKit                               0x0000000104032a33 -[UIApplication sendEvent:] + 371
	16  UIKit                               0x0000000113883959 -[UIApplicationAccessibility sendEvent:] + 93
	17  UIKit                               0x0000000104824b6d __dispatchPreprocessedEventFromEventQueue + 3248
	18  UIKit                               0x000000010481d817 __handleEventQueue + 4879
	19  CoreFoundation                      0x0000000103486311 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	20  CoreFoundation                      0x000000010346b59c __CFRunLoopDoSources0 + 556
	21  CoreFoundation                      0x000000010346aa86 __CFRunLoopRun + 918
	22  CoreFoundation                      0x000000010346a494 CFRunLoopRunSpecific + 420
	23  GraphicsServices                    0x0000000108925a6f GSEventRunModal + 161
	24  UIKit                               0x0000000104014f34 UIApplicationMain + 159
	25  PPStickerKeyboard                   0x000000010294fc6f main + 111
	26  libdyld.dylib                       0x00000001069cc68d start + 1
)

**Comment by VernonVan** [comment]
晚些时候我会查看这个问题~

**Comment by BennerZhang** [comment]
好的，麻烦你了

**Comment by VernonVan** [comment]
@BennerZhang 崩溃是因为我在文件 PPStickerKeyboard 中没有判断系统版本直接使用了 ```UIApplication.sharedApplication.delegate.window.safeAreaInsets``` 方法，这个方法最低支持 iOS11
我已经修复了这个问题，你可以 clone 查看，有其他问题可以找我~
