### ISSUE TITLE
键盘与输入框间隙问题

### ISSUE THREAD

**Issue by WuGaoSheng0207** [VernonVan/PPStickerKeyboard#5]
大佬，您这个写得真好，我在用到你写的这个输入框的时候，由于需求的不一样，在输入框外头稍微加了点东西，偶尔会出现输入框与下方键盘之间出现空白区域。尤其是从表情键盘切换回文字键盘时，必现。这是什么原因哦？我之前写的键盘也是出现这种空白区域，后来是搞了个骚操作，对于您的这个作品我觉得很完美，不太敢改动您的源码，您知道为什么吗？谢谢！

**Comment by VernonVan** [comment]
是因为表情键盘和文字键盘的高度不一样，然后切换的时候没有 keyboardWillShow 的通知，所以没有更新输入框的 frame，可以试试垫个白色的视图盖住的骚操作。

**Comment by WuGaoSheng0207** [comment]
哈哈，我想的骚操作就是这个。不过这不是解决问题的根本方法。那个空白的部分，在不切换表情键盘时，也有可能会出现，就是那个输入框会弹动一下，然后，中间出现一个可以看到下面部分试图的部分。我之前封装的键盘也是这样。谢谢您的回复，我就先这样了，以后想明白了，再改。
